### ISSUE TITLE
Service role

### ISSUE THREAD

**Issue by srirachanaachyuthuni** [awslabs/gaming-analytics-pipeline#2]
In the gaming-analytics-pipeline.yml template, in configuration templates - CronConnectorConfigurationTemplate, s3ConnectorConfigurationTemplate and redshiftConnectorConfigurationTemplate, Service role is hardcoded - arn:aws:iam::208800812415:role/aws-elasticbeanstalk-service-role  which causes issues during creation. 

This should be modified to - aws-elasticbeanstalk-service-role as follows, in all the three resources:
 -  Namespace: "aws:ElasticBeanstalk:environment"
     OptionName: "ServiceRole"
     Value: "aws-elasticbeanstalk-service-role"

**Comment by thomasphorton** [comment]
Thank you! We have a fix for this in testing right now, and I'll update you when it is released.
